baseURL = 'https://rcrcusa.com/'
languageCode = 'en-us'
title = 'RC RC USA'
enableRobotsTXT = true

[params]
  description = "Discover the greatest 1:18 and 1:24 scale indoor RC crawler course in Colorado Springs. Bring your own rig or rent one and conquer our custom-built terrains!"

[taxonomies]
  tag = ""
  category = ""