baseURL = 'https://rcrcusa.com/'
languageCode = 'en-us'
title = 'RC RC USA'

[params]
  description = "Colorado Springs Greatest 1:18 & 1:24 - Scale Crawler Course"

[taxonomies]
  tag = ""
  category = ""